transformations:
  - clean_raw_data
  - normalize_addresses_column
  - remove_invalid_dealerships
  - fill_missing_cities
  - normalize_columns_to_constants
  - convert_data_types
  - normalize_group_by_latest